const vendors = [
  {
    name: 'Atlas Industrial Supply',
    category: 'Packaging',
    contactName: 'Riya Malhotra',
    contactPhone: '+91 98765 12001',
    contactEmail: 'riya@atlasindustrial.example',
    quotedPrice: 4200,
    shippingCost: 320,
    leadTimeDays: 5,
    notes: 'Reliable regional supplier with same-week dispatch.',
  },
  {
    name: 'BluePeak Materials',
    category: 'Packaging',
    contactName: 'Karan Sethi',
    contactPhone: '+91 98765 12002',
    contactEmail: 'karan@bluepeak.example',
    quotedPrice: 3980,
    shippingCost: 520,
    leadTimeDays: 7,
    notes: 'Best unit pricing but longer interstate transit.',
  },
  {
    name: 'Cedar Fleet Works',
    category: 'Maintenance',
    contactName: 'Ananya Rao',
    contactPhone: '+91 98765 12003',
    contactEmail: 'ananya@cedarfleet.example',
    quotedPrice: 6100,
    shippingCost: 450,
    leadTimeDays: 4,
    notes: 'Fast delivery and strong after-sales support.',
  },
  {
    name: 'Delta Office Essentials',
    category: 'Office',
    contactName: 'Vikram Joshi',
    contactPhone: '+91 98765 12004',
    contactEmail: 'vikram@deltaoffice.example',
    quotedPrice: 2750,
    shippingCost: 300,
    leadTimeDays: 6,
    notes: 'Balanced quote suited for recurring restocks.',
  },
  {
    name: 'Everlane Safety Co.',
    category: 'Safety',
    contactName: 'Megha Kapoor',
    contactPhone: '+91 98765 12005',
    contactEmail: 'megha@everlanesafety.example',
    quotedPrice: 3550,
    shippingCost: 180,
    leadTimeDays: 3,
    notes: 'Fastest turnaround and strong stock availability.',
  },
  {
    name: 'ForgeLine Procurement',
    category: 'Maintenance',
    contactName: 'Arjun Nair',
    contactPhone: '+91 98765 12006',
    contactEmail: 'arjun@forgeline.example',
    quotedPrice: 5840,
    shippingCost: 640,
    leadTimeDays: 8,
    notes: 'Higher landed cost but broad maintenance catalog.',
  },
];

module.exports = { vendors };
