const vendorSeeds = [
  ['Atlas Industrial Supply', 'Packaging', 'Riya Malhotra', 4200, 320, 5, 'Reliable regional supplier with same-week dispatch.'],
  ['BluePeak Materials', 'Packaging', 'Karan Sethi', 3980, 520, 7, 'Best unit pricing but longer interstate transit.'],
  ['Cedar Fleet Works', 'Maintenance', 'Ananya Rao', 6100, 450, 4, 'Fast delivery and strong after-sales support.'],
  ['Delta Office Essentials', 'Office', 'Vikram Joshi', 2750, 300, 6, 'Balanced quote suited for recurring restocks.'],
  ['Everlane Safety Co.', 'Safety', 'Megha Kapoor', 3550, 180, 3, 'Fastest turnaround and strong stock availability.'],
  ['ForgeLine Procurement', 'Maintenance', 'Arjun Nair', 5840, 640, 8, 'Higher landed cost but broad maintenance catalog.'],
  ['Granite Carton Works', 'Packaging', 'Neha Bhatia', 4410, 260, 4, 'Good dispatch reliability for recurring carton orders.'],
  ['Harborline Tools', 'Maintenance', 'Siddharth Menon', 5520, 410, 5, 'Strong service turnaround and good tool warranty terms.'],
  ['Ivory Stationers', 'Office', 'Pooja Talreja', 2920, 210, 3, 'Fast office consumables supply with low logistics risk.'],
  ['Juniper Safe Gear', 'Safety', 'Manav Arora', 3680, 220, 4, 'Competitive safety gear pricing with dependable packing.'],
  ['Keystone Industrial', 'Packaging', 'Bhavya Shah', 4620, 330, 6, 'Suitable for medium-volume supply planning.'],
  ['Lattice Procurement Hub', 'Office', 'Rohit Bansal', 3180, 245, 5, 'Strong catalog breadth and clean invoice support.'],
  ['Morrow Field Supplies', 'Safety', 'Aisha Khan', 3490, 205, 2, 'Best emergency fulfilment lead time in this batch.'],
  ['Northcrest Fabrication', 'Maintenance', 'Dev Mehta', 6280, 530, 6, 'Higher cost but very dependable delivery windows.'],
  ['Oakline Packaging Co.', 'Packaging', 'Simran Kaur', 4095, 275, 4, 'Balanced landed cost and responsive account management.'],
  ['PrimeLot Essentials', 'Office', 'Yashvi Desai', 3010, 185, 4, 'Clean quote structure and quick replenishment capability.'],
  ['Quartz Safety Systems', 'Safety', 'Ishaan Tiwari', 3890, 165, 5, 'Strong compliance documentation and predictable dispatch.'],
  ['RedRiver Industrial', 'Maintenance', 'Tanvi Soni', 5970, 490, 7, 'Stable vendor with decent pricing on bundled orders.'],
  ['Summit Carton House', 'Packaging', 'Harsh Vora', 3875, 340, 5, 'Low quote with acceptable shipping overhead.'],
  ['TrueNorth Office Goods', 'Office', 'Khushi Jain', 2860, 240, 6, 'Reliable restock option for monthly procurement cycles.'],
  ['Union Shield Works', 'Safety', 'Varun Chhabra', 3610, 190, 4, 'Good safety inventory depth and responsive support.'],
  ['Vertex Plant Supply', 'Maintenance', 'Nikita Paul', 5755, 355, 5, 'Good landed cost for plant maintenance purchases.'],
  ['WillowPack Industries', 'Packaging', 'Sana Sheikh', 4340, 295, 3, 'Fast dispatch and good carton quality consistency.'],
  ['Xeno Facility Mart', 'Office', 'Aditya Lamba', 3270, 215, 5, 'Useful for mixed office supply bundles.'],
  ['YieldSafe Commerce', 'Safety', 'Rohan Ghosh', 3420, 230, 3, 'Strong pricing and quick fulfilment for urgent orders.'],
  ['Zenith Maintenance Co.', 'Maintenance', 'Priya Dutta', 6085, 365, 4, 'Premium quote but dependable execution quality.'],
  ['Amber Line Packaging', 'Packaging', 'Kriti Anand', 4015, 285, 6, 'Consistent packaging stock with moderate lead time.'],
  ['Beacon Workplace Supply', 'Office', 'Samar Oberoi', 3090, 260, 4, 'Well suited for routine office procurement.'],
  ['Cobalt Safety Network', 'Safety', 'Lavanya Iyer', 3745, 175, 5, 'Reliable documentation and consistent packing quality.'],
  ['Driftwood Repair Partners', 'Maintenance', 'Rahul Pathak', 5890, 445, 6, 'Good maintenance option for non-urgent workloads.'],
];

const vendors = vendorSeeds.map(
  ([name, category, contactName, quotedPrice, shippingCost, leadTimeDays, notes], index) => ({
    id: index + 1,
    name,
    category,
    contactName,
    contactPhone: `+91 98765 ${String(12001 + index).padStart(5, '0')}`,
    contactEmail: `${name.toLowerCase().replaceAll(/[^a-z0-9]+/g, '')}@example.com`,
    quotedPrice,
    shippingCost,
    leadTimeDays,
    notes,
  }),
);

module.exports = { vendors };
